descriptionFormat: '{product.title} - {title}'
enableVersioning: false
handle: tapesMembranes
hasDimensions: true
hasProductTitleField: true
hasVariantTitleField: true
maxVariants: null
name: 'Tapes and Membranes'
productFieldLayouts:
  1b221bcb-31d4-4e65-96d1-ee72f69b95d0:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2024-10-10T19:59:31+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\commerce\fieldlayoutelements\ProductTitleField
            uid: 3f61aa11-a4b2-4147-bd36-082a5c2e3eea
            userCondition: null
            warning: null
            width: 100
          -
            attribute: variants
            dateAdded: '2024-10-10T19:59:31+00:00'
            elementCondition: null
            id: null
            includeInCards: false
            instructions: null
            label: null
            mandatory: true
            orientation: null
            providesThumbs: false
            requirable: false
            required: false
            tip: null
            translatable: false
            type: craft\commerce\fieldlayoutelements\VariantsField
            uid: 7e894643-d637-4094-a515-ff56feb76c40
            userCondition: null
            warning: null
        name: Content
        uid: 4b2c0ebb-de0d-40d1-915f-ec376dc6dec6
        userCondition: null
productTitleFormat: ''
productTitleTranslationKeyFormat: null
productTitleTranslationMethod: site
propagationMethod: all
siteSettings:
  24b1554e-bb4c-4639-aaa1-13d20c08f54c: # Five Merchants
    enabledByDefault: true
    hasUrls: true
    template: ''
    uriFormat: 'tapes-and-membranes/{slug}'
skuFormat: ''
variantFieldLayouts:
  a02d930e-cce8-4b18-baa0-365b26986302:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2024-10-10T19:59:31+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\commerce\fieldlayoutelements\VariantTitleField
            uid: cdd27a86-2304-44c2-842d-a5d4fe040899
            userCondition: null
            warning: null
            width: 100
          -
            attribute: sku
            dateAdded: '2024-10-10T19:59:31+00:00'
            elementCondition: null
            id: null
            includeInCards: false
            instructions: null
            label: SKU
            mandatory: true
            orientation: null
            providesThumbs: false
            requirable: false
            required: true
            tip: null
            translatable: false
            type: craft\commerce\fieldlayoutelements\PurchasableSkuField
            uid: 1a2a3853-63db-4fdb-96f4-12d31f8a2fb9
            userCondition: null
            warning: null
            width: 100
          -
            attribute: price
            dateAdded: '2024-10-10T19:59:31+00:00'
            elementCondition: null
            id: null
            includeInCards: false
            instructions: null
            label: __blank__
            mandatory: true
            orientation: null
            providesThumbs: false
            requirable: false
            required: true
            tip: null
            translatable: false
            type: craft\commerce\fieldlayoutelements\PurchasablePriceField
            uid: 3d682587-4a70-4c51-b367-26fa5e80a17b
            userCondition: null
            warning: null
            width: 100
          -
            attribute: stock
            dateAdded: '2024-10-10T19:59:31+00:00'
            elementCondition: null
            id: null
            includeInCards: false
            instructions: null
            label: Inventory
            mandatory: true
            orientation: null
            providesThumbs: false
            requirable: false
            required: true
            tip: null
            translatable: false
            type: craft\commerce\fieldlayoutelements\PurchasableStockField
            uid: a4604193-ae5c-4308-8eb8-aa69db3d60e6
            userCondition: null
            warning: null
            width: 100
          -
            attribute: availableForPurchase
            dateAdded: '2024-10-10T19:59:31+00:00'
            elementCondition: null
            id: null
            includeInCards: false
            instructions: null
            label: 'Available for purchase'
            mandatory: true
            orientation: null
            providesThumbs: false
            requirable: false
            required: true
            tip: null
            translatable: false
            type: craft\commerce\fieldlayoutelements\PurchasableAvailableForPurchaseField
            uid: 56548bce-c872-47f9-b3af-afcdb19b68e4
            userCondition: null
            warning: null
            width: 100
          -
            attribute: allowedQty
            dateAdded: '2024-10-10T19:59:31+00:00'
            elementCondition: null
            id: null
            includeInCards: false
            instructions: null
            label: 'Allowed Qty'
            mandatory: true
            orientation: null
            providesThumbs: false
            requirable: false
            required: false
            tip: null
            translatable: false
            type: craft\commerce\fieldlayoutelements\PurchasableAllowedQtyField
            uid: 63c5729d-55b7-4d33-b54e-4f334f10d693
            userCondition: null
            warning: null
            width: 100
          -
            attribute: freeShipping
            dateAdded: '2024-10-10T19:59:31+00:00'
            elementCondition: null
            id: null
            includeInCards: false
            instructions: null
            label: 'Free Shipping'
            mandatory: true
            orientation: null
            providesThumbs: false
            requirable: false
            required: true
            tip: null
            translatable: false
            type: craft\commerce\fieldlayoutelements\PurchasableFreeShippingField
            uid: c63ddc29-8d9a-4b92-bd45-1dde32f3ca8e
            userCondition: null
            warning: null
            width: 100
          -
            attribute: promotable
            dateAdded: '2024-10-10T19:59:31+00:00'
            elementCondition: null
            id: null
            includeInCards: false
            instructions: null
            label: Promotable
            mandatory: true
            orientation: null
            providesThumbs: false
            requirable: false
            required: true
            tip: null
            translatable: false
            type: craft\commerce\fieldlayoutelements\PurchasablePromotableField
            uid: 63fcff2a-b821-44d9-8dbb-949934fe0c55
            userCondition: null
            warning: null
            width: 100
          -
            attribute: dimensions
            dateAdded: '2024-10-10T19:59:31+00:00'
            elementCondition: null
            id: null
            includeInCards: false
            instructions: null
            label: Dimensions
            mandatory: true
            orientation: null
            providesThumbs: false
            requirable: false
            required: false
            tip: null
            translatable: false
            type: craft\commerce\fieldlayoutelements\PurchasableDimensionsField
            uid: 170799d9-c986-4981-8b5e-b64115234c72
            userCondition: null
            warning: null
            width: 100
          -
            attribute: weight
            dateAdded: '2024-10-10T19:59:31+00:00'
            elementCondition: null
            id: null
            includeInCards: false
            instructions: null
            label: Weight
            mandatory: true
            orientation: null
            providesThumbs: false
            requirable: false
            required: false
            tip: null
            translatable: false
            type: craft\commerce\fieldlayoutelements\PurchasableWeightField
            uid: 80c6e9a6-18e8-444b-a612-f4c485799822
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: abb0d7a5-3fea-413d-8c75-661172c89ffa
        userCondition: null
variantTitleFormat: '{product.title}'
variantTitleTranslationKeyFormat: null
variantTitleTranslationMethod: site
