color: null
fieldLayouts:
  ac532f2b-0958-487e-8023-209db57c2d99:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2024-10-01T20:49:07+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: cb573e77-4608-4633-9f0f-feed3305325a
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-10-01T21:09:38+00:00'
            elementCondition: null
            fieldUid: c2f33fbf-f2dd-4e2c-a73d-8fdb0b2a8e62 # Body text
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: b4ca4c0d-de91-4f67-afbb-59782cc4db00
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: aefed431-57f0-49ab-a182-89fcce93ca69
        userCondition: null
handle: accordionContent
hasTitleField: true
icon: ''
name: 'Accordion Content'
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: ''
titleTranslationKeyFormat: null
titleTranslationMethod: site
