color: null
fieldLayouts:
  c289bd4b-3d21-4c81-b80e-a04e4ee9ef75:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2024-10-10T03:08:51+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: d9930587-85cc-4367-bc4d-fb0ce8cde34b
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-10-10T03:17:39+00:00'
            elementCondition: null
            fieldUid: c2f33fbf-f2dd-4e2c-a73d-8fdb0b2a8e62 # Body text
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 2dab89ce-6c58-44e1-939a-7972923f2495
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-10-10T03:17:39+00:00'
            elementCondition: null
            fieldUid: 9c5edb31-d275-4b0d-88b7-a8f1395e194c # Button Text
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 08183621-094f-4902-bc6f-e6995a03e660
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-10-10T03:20:34+00:00'
            elementCondition: null
            fieldUid: 9642a918-c523-42c5-b282-682e9739bfc3 # Button Link
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: df1677d1-c120-4cd6-88e0-6ec2895e807e
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-10-10T03:17:39+00:00'
            elementCondition: null
            fieldUid: e4bcf9a3-fd68-455d-aa8c-b60cc9a5d8da # Image
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 66bd2e67-47d1-4b2f-b4a2-6779237385b5
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-10-10T03:17:39+00:00'
            elementCondition: null
            heading: ''
            type: craft\fieldlayoutelements\Heading
            uid: 70d9df51-6a5d-4ff2-9855-a7ca5835820a
            userCondition: null
          -
            dateAdded: '2024-10-10T03:17:39+00:00'
            elementCondition: null
            fieldUid: 046855ef-71bb-4c67-a58a-356e4bd73c27 # Heading
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: ef3077b1-4d53-4071-870b-70c9a5f238b9
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-10-10T03:17:39+00:00'
            elementCondition: null
            fieldUid: c2f33fbf-f2dd-4e2c-a73d-8fdb0b2a8e62 # Body text
            handle: bodyText2
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 6294c6c0-c652-440b-bcd7-358c9d5f4fc4
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-10-10T03:20:34+00:00'
            elementCondition: null
            fieldUid: 9c5edb31-d275-4b0d-88b7-a8f1395e194c # Button Text
            handle: buttonText2
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 7a592ffc-ccdb-48b8-8d58-ca17290741d4
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-10-10T03:20:34+00:00'
            elementCondition: null
            fieldUid: 9642a918-c523-42c5-b282-682e9739bfc3 # Button Link
            handle: buttonLink2
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 0e3e25b6-f449-4a31-82af-880f17b9fec1
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-10-10T03:17:39+00:00'
            elementCondition: null
            heading: ''
            type: craft\fieldlayoutelements\Heading
            uid: ca02a293-fb51-4633-b64c-ed1b7372bd62
            userCondition: null
          -
            dateAdded: '2024-10-10T03:17:39+00:00'
            elementCondition: null
            fieldUid: e4bcf9a3-fd68-455d-aa8c-b60cc9a5d8da # Image
            handle: image2
            includeInCards: false
            instructions: null
            label: 'Logo Image'
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 70b286c4-c456-4c7c-8ad2-2d6d746b55a4
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-10-10T03:17:39+00:00'
            elementCondition: null
            fieldUid: c2f33fbf-f2dd-4e2c-a73d-8fdb0b2a8e62 # Body text
            handle: bodyText3
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 4d7b0903-e2dc-4e65-9bbc-f9daccef14ad
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-10-10T03:20:34+00:00'
            elementCondition: null
            fieldUid: 9c5edb31-d275-4b0d-88b7-a8f1395e194c # Button Text
            handle: buttonText3
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: d456db91-04c3-4867-99b5-e64b8325fabd
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-10-10T03:20:34+00:00'
            elementCondition: null
            fieldUid: 9642a918-c523-42c5-b282-682e9739bfc3 # Button Link
            handle: buttonLink3
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 393320ea-67bd-4f7a-a380-dcef12cb8d89
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-10-10T03:17:39+00:00'
            elementCondition: null
            fieldUid: e4bcf9a3-fd68-455d-aa8c-b60cc9a5d8da # Image
            handle: image3
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: ff2a4cbd-ae9c-4b2c-bc22-53fca931fcbe
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-10-10T03:17:39+00:00'
            elementCondition: null
            heading: 'Form section'
            type: craft\fieldlayoutelements\Heading
            uid: 41b87cf7-ea18-4c9a-ada7-42e305b060ce
            userCondition: null
          -
            dateAdded: '2024-10-10T03:17:39+00:00'
            elementCondition: null
            fieldUid: 046855ef-71bb-4c67-a58a-356e4bd73c27 # Heading
            handle: heading2
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 519ee06c-e70c-4c11-b16a-2f02a135b8a0
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 5393fa5f-39a9-4044-8b1f-991d4e4df039
        userCondition: null
handle: airWeatherTightness
hasTitleField: true
icon: ''
name: 'Air Weather Tightness'
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: ''
titleTranslationKeyFormat: null
titleTranslationMethod: site
