color: null
fieldLayouts:
  41a995ed-b312-48fb-a6f1-aa8c1e037751:
    tabs:
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2024-11-12T10:49:57+13:00'
            elementCondition: null
            fieldUid: a650c39c-96a6-495e-8b5d-1381ba9ac205
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: a650c39c-96a6-495e-8b5d-1381ba9ac205
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-11-12T10:49:57+13:00'
            elementCondition: null
            fieldUid: d9fcee47-1fb4-460d-83ae-10d517940a7e
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: d9fcee47-1fb4-460d-83ae-10d517940a7e
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-11-12T10:49:57+13:00'
            elementCondition: null
            fieldUid: 01f4e02c-9584-4b9c-8d83-82ea561868a7
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 01f4e02c-9584-4b9c-8d83-82ea561868a7
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-11-12T10:49:57+13:00'
            elementCondition: null
            fieldUid: 8de5d13c-a82f-4563-b0ce-a3351df1c568
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 8de5d13c-a82f-4563-b0ce-a3351df1c568
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 51d00d42-e35b-4c9e-99db-9bbe948eec1e
        userCondition: null
handle: checkboxes
hasTitleField: false
icon: null
name: CheckBoxes
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
