color: null
fieldLayouts:
  95b05fc2-ba85-49c3-85e5-97aacbcae84d:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2024-10-14T22:31:20+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 09da7836-68a7-4279-91b8-5167010dad07
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-10-14T22:34:47+00:00'
            elementCondition: null
            fieldUid: 046855ef-71bb-4c67-a58a-356e4bd73c27 # Heading
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 1bc691ac-0e4a-4340-9f69-08cca826b0f1
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-10-14T22:34:47+00:00'
            elementCondition: null
            fieldUid: c2f33fbf-f2dd-4e2c-a73d-8fdb0b2a8e62 # Body text
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 64cef37b-bad0-4ef4-b91f-3e3ffa15c875
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: f19a46bb-3069-45eb-9b14-82eb8fff81e0
        userCondition: null
handle: conditionsTemplate
hasTitleField: false
icon: ''
name: 'Conditions Template'
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: '{entry.slug}'
titleTranslationKeyFormat: null
titleTranslationMethod: site
