color: null
fieldLayouts:
  3f765957-c21b-4549-b327-85a5fd857e86:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2024-10-14T21:55:37+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: de876216-44b7-4369-9014-dbdb0d7a653c
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-10-14T21:59:18+00:00'
            elementCondition: null
            fieldUid: 046855ef-71bb-4c67-a58a-356e4bd73c27 # Heading
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 64526840-dfe2-403c-af5a-9d6788f924f0
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-10-14T21:57:21+00:00'
            elementCondition: null
            fieldUid: c2f33fbf-f2dd-4e2c-a73d-8fdb0b2a8e62 # Body text
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 4af47159-8330-4ded-b2fb-17d690dfd41e
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 6c16a988-99a5-459e-b07a-46c4c4bf8354
        userCondition: null
handle: contact
hasTitleField: false
icon: ''
name: Contact
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: Contact
titleTranslationKeyFormat: null
titleTranslationMethod: site
