color: null
fieldLayouts:
  b84c66dd-ba78-4b9e-acca-62a3889e1b39:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2024-10-03T21:26:22+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: 'Title is optional'
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: c870a7b8-7814-47fb-9c13-837915b45767
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-10-08T02:26:41+00:00'
            elementCondition: null
            fieldUid: 046855ef-71bb-4c67-a58a-356e4bd73c27 # Heading
            handle: null
            includeInCards: false
            instructions: 'Heading is optional'
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 7f084900-a272-4a5e-9449-2012212ef374
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-10-03T21:28:07+00:00'
            elementCondition: null
            fieldUid: c2f33fbf-f2dd-4e2c-a73d-8fdb0b2a8e62 # Body text
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: f332f399-9e36-4e63-a42a-86a5970d6204
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-10-03T21:28:07+00:00'
            elementCondition: null
            fieldUid: c2f33fbf-f2dd-4e2c-a73d-8fdb0b2a8e62 # Body text
            handle: bodyText2
            includeInCards: false
            instructions: null
            label: Price
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 36070615-55bc-4b11-9548-297d1ede3747
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 09699dd8-a13c-4eec-9ace-6ef2ea72dcd6
        userCondition: null
handle: costSection
hasTitleField: false
icon: ''
name: 'Cost Section'
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: '{ heading|default(''cost-heading'') }'
titleTranslationKeyFormat: null
titleTranslationMethod: site
