color: null
fieldLayouts:
  cf35cc05-f92b-4a27-8697-cbd3954b7e7f:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2024-09-29T22:31:21+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 8ca2b1e6-627f-4c36-be60-5a7504dc6cd3
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-09-30T03:06:07+00:00'
            elementCondition: null
            fieldUid: 046855ef-71bb-4c67-a58a-356e4bd73c27 # Heading
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: d57a83d8-d39a-472a-8640-4858722b2476
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-09-30T03:06:07+00:00'
            elementCondition: null
            fieldUid: c2f33fbf-f2dd-4e2c-a73d-8fdb0b2a8e62 # Body text
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: d73dfc69-67e7-4a6d-9351-cc894e5b3faf
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-09-30T20:11:46+00:00'
            elementCondition: null
            fieldUid: 9c5edb31-d275-4b0d-88b7-a8f1395e194c # Button Text
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 327961c7-ca43-47db-98d6-a4c5dff6f7dd
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-09-30T20:11:46+00:00'
            elementCondition: null
            fieldUid: 9642a918-c523-42c5-b282-682e9739bfc3 # Button Link
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 8bcb8603-a4c4-4d7c-b504-db577575ea33
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-09-30T20:36:48+00:00'
            elementCondition: null
            fieldUid: e4bcf9a3-fd68-455d-aa8c-b60cc9a5d8da # Image
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 8f80d1e6-2df3-4f05-9e00-fc1af73e3da8
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-09-30T20:04:05+00:00'
            elementCondition: null
            type: craft\fieldlayoutelements\HorizontalRule
            uid: 819b4e5f-11ba-434a-b1b4-6cd4494d2409
            userCondition: null
          -
            dateAdded: '2024-09-30T20:04:05+00:00'
            elementCondition: null
            fieldUid: 046855ef-71bb-4c67-a58a-356e4bd73c27 # Heading
            handle: heading2
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: f6a30f9a-c4e6-40b3-a9ac-ae793536110f
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-09-30T20:04:05+00:00'
            elementCondition: null
            fieldUid: c2f33fbf-f2dd-4e2c-a73d-8fdb0b2a8e62 # Body text
            handle: bodyText2
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: cc9e41a0-bdbb-44c7-8243-8c72804769f3
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-09-30T20:19:23+00:00'
            elementCondition: null
            fieldUid: 9c5edb31-d275-4b0d-88b7-a8f1395e194c # Button Text
            handle: buttonText2
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 11606e94-891f-492a-9b52-a80c2c05b702
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-09-30T20:19:23+00:00'
            elementCondition: null
            fieldUid: 9642a918-c523-42c5-b282-682e9739bfc3 # Button Link
            handle: buttonLink2
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 0c3ecb83-eca5-4b64-8aa7-0312796dd9a4
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-09-30T20:42:19+00:00'
            elementCondition: null
            fieldUid: e4bcf9a3-fd68-455d-aa8c-b60cc9a5d8da # Image
            handle: image2
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: d82e43c5-1169-4820-9805-ab716ca4f676
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-09-30T20:06:10+00:00'
            elementCondition: null
            type: craft\fieldlayoutelements\HorizontalRule
            uid: 3e6b041f-c7e7-4e85-ab8c-9ad70887ff2d
            userCondition: null
          -
            dateAdded: '2024-09-30T20:06:10+00:00'
            elementCondition: null
            fieldUid: 046855ef-71bb-4c67-a58a-356e4bd73c27 # Heading
            handle: heading3
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 3df84491-ab3a-4c82-8aa0-37b76df904b3
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-09-30T20:06:10+00:00'
            elementCondition: null
            fieldUid: c2f33fbf-f2dd-4e2c-a73d-8fdb0b2a8e62 # Body text
            handle: bodyText3
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 784e0277-e796-459b-b765-9dfbb9c1a2be
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-09-30T20:19:23+00:00'
            elementCondition: null
            fieldUid: 9c5edb31-d275-4b0d-88b7-a8f1395e194c # Button Text
            handle: buttonText3
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 362ef51a-98a0-40f8-978d-baeb971a06c1
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-09-30T20:19:23+00:00'
            elementCondition: null
            fieldUid: 9642a918-c523-42c5-b282-682e9739bfc3 # Button Link
            handle: buttonLink3
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: c8aeaf74-b61e-4bcc-99fd-28263c3b4bbc
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-09-30T20:08:02+00:00'
            elementCondition: null
            type: craft\fieldlayoutelements\HorizontalRule
            uid: 64cf4c92-b928-4885-90ce-1ff532e8c0e2
            userCondition: null
          -
            dateAdded: '2024-09-30T20:06:10+00:00'
            elementCondition: null
            fieldUid: 046855ef-71bb-4c67-a58a-356e4bd73c27 # Heading
            handle: heading4
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: f6ac3210-762e-472b-a4d1-9c12c1c93965
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-09-30T20:06:10+00:00'
            elementCondition: null
            fieldUid: c2f33fbf-f2dd-4e2c-a73d-8fdb0b2a8e62 # Body text
            handle: bodyText4
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 1804a66b-d353-41d8-93a3-73ffae295f3e
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-09-30T20:25:19+00:00'
            elementCondition: null
            type: craft\fieldlayoutelements\HorizontalRule
            uid: 41347551-f680-48c6-8d0c-9bbaa849bd88
            userCondition: null
          -
            dateAdded: '2024-09-30T20:25:19+00:00'
            elementCondition: null
            fieldUid: 046855ef-71bb-4c67-a58a-356e4bd73c27 # Heading
            handle: heading5
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 74299c42-fc72-4d66-953b-1add50f253f2
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-09-30T20:26:39+00:00'
            elementCondition: null
            type: craft\fieldlayoutelements\HorizontalRule
            uid: d870d690-f504-464b-8752-0bcb9bca9de9
            userCondition: null
          -
            dateAdded: '2024-09-30T20:25:19+00:00'
            elementCondition: null
            fieldUid: 046855ef-71bb-4c67-a58a-356e4bd73c27 # Heading
            handle: heading6
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: fe814f69-7d0f-4a11-8da4-9f7a40fdb1cb
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-09-30T20:25:19+00:00'
            elementCondition: null
            type: craft\fieldlayoutelements\HorizontalRule
            uid: 48c5ac74-457a-4569-9601-f15d386dac63
            userCondition: null
          -
            dateAdded: '2024-09-30T20:26:39+00:00'
            elementCondition: null
            fieldUid: 046855ef-71bb-4c67-a58a-356e4bd73c27 # Heading
            handle: heading7
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 4529f6be-3d21-4242-93a4-3cae76c78e93
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 6d6a8356-f8c0-4412-87cc-d4aeecc89048
        userCondition: null
handle: home
hasTitleField: true
icon: ''
name: home
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: ''
titleTranslationKeyFormat: null
titleTranslationMethod: site
