color: null
fieldLayouts:
  2653ff23-d4f2-45a7-aca6-012855b0e4f3:
    tabs:
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2024-09-30T22:26:34+00:00'
            elementCondition: null
            fieldUid: 046855ef-71bb-4c67-a58a-356e4bd73c27 # Heading
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 1217df6b-1a39-4ca9-8f08-849f5e4e6d82
            userCondition: null
            warning: null
            width: 100
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2024-09-30T21:22:06+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: ec846d84-199b-44a7-91c0-33feace644ea
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-09-30T22:00:32+00:00'
            elementCondition: null
            fieldUid: c2f33fbf-f2dd-4e2c-a73d-8fdb0b2a8e62 # Body text
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: ba3b4bdd-7dc4-4096-a7cd-744699b788d4
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-09-30T22:00:32+00:00'
            elementCondition: null
            fieldUid: 9c5edb31-d275-4b0d-88b7-a8f1395e194c # Button Text
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: eead972e-650d-4e36-aa31-31303830c8da
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-09-30T22:00:32+00:00'
            elementCondition: null
            fieldUid: 9642a918-c523-42c5-b282-682e9739bfc3 # Button Link
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 18e55aaa-6c54-4784-b7af-fd544cf54d24
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-09-30T22:00:32+00:00'
            elementCondition: null
            fieldUid: e4bcf9a3-fd68-455d-aa8c-b60cc9a5d8da # Image
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 1d828f07-683c-4242-8585-8087770a295e
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-10-07T21:20:47+00:00'
            elementCondition: null
            heading: 'Second content section'
            type: craft\fieldlayoutelements\Heading
            uid: 5528a130-4874-4946-a185-cc61db107648
            userCondition: null
          -
            dateAdded: '2024-09-30T22:00:32+00:00'
            elementCondition: null
            fieldUid: e4bcf9a3-fd68-455d-aa8c-b60cc9a5d8da # Image
            handle: image2
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: fa4127ab-1357-48bd-9096-c8fef4c6e54f
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-09-30T22:00:32+00:00'
            elementCondition: null
            fieldUid: c2f33fbf-f2dd-4e2c-a73d-8fdb0b2a8e62 # Body text
            handle: bodyText2
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 7609a7b8-3041-4943-9f7e-cfef29d2dabf
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-10-07T21:20:47+00:00'
            elementCondition: null
            heading: 'Visual Diagram Section'
            type: craft\fieldlayoutelements\Heading
            uid: de198e85-9428-4934-8a8f-08423c73bec8
            userCondition: null
          -
            dateAdded: '2024-10-01T02:32:16+00:00'
            elementCondition: null
            fieldUid: 046855ef-71bb-4c67-a58a-356e4bd73c27 # Heading
            handle: heading2
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 68172c81-7a1f-4dd3-81d4-61ab7b3ed61e
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-10-01T01:27:13+00:00'
            elementCondition: null
            fieldUid: c2f33fbf-f2dd-4e2c-a73d-8fdb0b2a8e62 # Body text
            handle: bodyText3
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 7f85ab26-2844-4832-ba77-b540976e7e4b
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-10-01T01:27:13+00:00'
            elementCondition: null
            fieldUid: e4bcf9a3-fd68-455d-aa8c-b60cc9a5d8da # Image
            handle: image3
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: b063d84c-68a1-492c-866d-aeafbd09d48a
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-10-01T02:27:28+00:00'
            elementCondition: null
            fieldUid: c2f33fbf-f2dd-4e2c-a73d-8fdb0b2a8e62 # Body text
            handle: bodyText4
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 9c81a1da-e6bd-4ba7-93e7-3d4d78702738
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-10-01T02:27:28+00:00'
            elementCondition: null
            fieldUid: e4bcf9a3-fd68-455d-aa8c-b60cc9a5d8da # Image
            handle: image4
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 699684a6-d7fe-459d-b450-5d6c4ace1dd1
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-10-01T02:27:28+00:00'
            elementCondition: null
            fieldUid: c2f33fbf-f2dd-4e2c-a73d-8fdb0b2a8e62 # Body text
            handle: bodyText5
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: c4f23aa1-8b8f-4e37-a7b5-118922e5e070
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-10-01T02:27:28+00:00'
            elementCondition: null
            fieldUid: e4bcf9a3-fd68-455d-aa8c-b60cc9a5d8da # Image
            handle: image5
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 8c89d9ab-c9f0-4043-b378-9b4d753a6635
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-10-01T02:27:28+00:00'
            elementCondition: null
            fieldUid: c2f33fbf-f2dd-4e2c-a73d-8fdb0b2a8e62 # Body text
            handle: bodyText6
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 6247d770-c7a8-40a4-b268-a816dd5c6209
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-10-01T02:27:28+00:00'
            elementCondition: null
            fieldUid: e4bcf9a3-fd68-455d-aa8c-b60cc9a5d8da # Image
            handle: image6
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: b415fc58-f2da-4a9e-92b4-175bfda4e322
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-10-07T21:19:26+00:00'
            elementCondition: null
            heading: 'Cost Comparison '
            type: craft\fieldlayoutelements\Heading
            uid: 5c15493f-1ae9-4300-8264-62b60b2da580
            userCondition: null
          -
            dateAdded: '2024-10-07T22:00:30+00:00'
            elementCondition: null
            fieldUid: 046855ef-71bb-4c67-a58a-356e4bd73c27 # Heading
            handle: heading4
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 6887bd2d-7e3f-4560-b437-a1b0f8b6bfd5
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-10-03T21:31:16+00:00'
            elementCondition: null
            fieldUid: 590e462c-d8f1-494d-a963-8c4e4a68e089 # Cost Comparison
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 1506c789-6bd1-46a4-8454-ac2fc3dffe81
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-10-07T22:05:51+00:00'
            elementCondition: null
            fieldUid: c2f33fbf-f2dd-4e2c-a73d-8fdb0b2a8e62 # Body text
            handle: bodyText8
            includeInCards: false
            instructions: null
            label: 'Disclaimer text'
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: b4a02b31-468b-457e-b8f6-ed14b5172180
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-10-07T22:11:50+00:00'
            elementCondition: null
            fieldUid: 9c5edb31-d275-4b0d-88b7-a8f1395e194c # Button Text
            handle: buttonText2
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 48724d21-8f3e-49bb-a4f1-9751fafae278
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-10-07T21:19:26+00:00'
            elementCondition: null
            heading: 'FAQ section'
            type: craft\fieldlayoutelements\Heading
            uid: 1ec1fd80-70d5-4dfd-8ffa-d0de94833fe0
            userCondition: null
          -
            dateAdded: '2024-10-01T20:52:27+00:00'
            elementCondition: null
            fieldUid: 3291a89c-2f88-49a3-a831-8282d1f1fab3 # FAQ Accordion
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 8c0d0cdd-68c8-4f39-81bf-7531b50e4348
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-10-07T21:19:26+00:00'
            elementCondition: null
            heading: 'Form Section'
            type: craft\fieldlayoutelements\Heading
            uid: 321e5629-8413-435b-af59-5b680ea553cb
            userCondition: null
          -
            dateAdded: '2024-10-03T19:47:38+00:00'
            elementCondition: null
            fieldUid: 046855ef-71bb-4c67-a58a-356e4bd73c27 # Heading
            handle: heading3
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 9f06c694-ded2-42e5-8f56-9746f7db6855
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-10-03T19:47:38+00:00'
            elementCondition: null
            fieldUid: c2f33fbf-f2dd-4e2c-a73d-8fdb0b2a8e62 # Body text
            handle: bodyText7
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: ea8cfde2-a337-468b-8bf1-cd3e234887cf
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 100d26c4-2a04-4eb4-a5c4-f59a5aecd5df
        userCondition: null
handle: homePerformanceAudits
hasTitleField: false
icon: ''
name: 'Home performance audits'
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: 'Home Performance Audits'
titleTranslationKeyFormat: null
titleTranslationMethod: site
