color: null
fieldLayouts:
  79e1ad2d-45b0-4a6c-9e77-b28bc4daf395:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2024-10-09T20:58:03+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 2e4470fc-a1f0-44ca-941f-b85d1aa2ea63
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-10-09T21:46:45+00:00'
            elementCondition: null
            fieldUid: c2f33fbf-f2dd-4e2c-a73d-8fdb0b2a8e62 # Body text
            handle: bodyText4
            includeInCards: false
            instructions: null
            label: 'Intro Text'
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 4b9081e8-bbfa-4de9-8a62-63e180fac4cb
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-10-09T21:22:36+00:00'
            elementCondition: null
            fieldUid: 046855ef-71bb-4c67-a58a-356e4bd73c27 # Heading
            handle: heading3
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: fe33789c-6af0-4ada-bfa3-6512b866cba0
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-10-09T21:22:36+00:00'
            elementCondition: null
            fieldUid: c2f33fbf-f2dd-4e2c-a73d-8fdb0b2a8e62 # Body text
            handle: bodyText3
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: f502f36f-c12b-41d3-af06-ffc359015fa7
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-10-09T21:22:36+00:00'
            elementCondition: null
            heading: 'YouTube Video One'
            type: craft\fieldlayoutelements\Heading
            uid: fe1c7bc5-9d32-4deb-b385-c8772d06b8ef
            userCondition: null
          -
            dateAdded: '2024-10-09T21:14:47+00:00'
            elementCondition: null
            fieldUid: 5a6f471d-5675-470e-b4c4-8c9ae3bccd79 # Video Id
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 5316d18f-5473-451b-8bff-4233365ce874
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-10-09T21:14:47+00:00'
            elementCondition: null
            fieldUid: 046855ef-71bb-4c67-a58a-356e4bd73c27 # Heading
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 448bd751-dccd-4bf2-b616-581970e379d1
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-10-09T21:14:47+00:00'
            elementCondition: null
            fieldUid: c2f33fbf-f2dd-4e2c-a73d-8fdb0b2a8e62 # Body text
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 2f27d5b0-872c-485b-a5ef-ebba699c9f38
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-10-09T21:22:36+00:00'
            elementCondition: null
            heading: 'YouTube Video Two'
            type: craft\fieldlayoutelements\Heading
            uid: e5a7c734-346f-4f03-b697-b73d2e757c3c
            userCondition: null
          -
            dateAdded: '2024-10-09T21:14:47+00:00'
            elementCondition: null
            fieldUid: 5a6f471d-5675-470e-b4c4-8c9ae3bccd79 # Video Id
            handle: videoId2
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 26a3813f-61d7-43e0-9ace-55086077b95c
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-10-09T21:14:47+00:00'
            elementCondition: null
            fieldUid: 046855ef-71bb-4c67-a58a-356e4bd73c27 # Heading
            handle: heading2
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: e8b8e8f2-bd1b-483c-901c-4370f0ed985a
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-10-09T21:14:47+00:00'
            elementCondition: null
            fieldUid: c2f33fbf-f2dd-4e2c-a73d-8fdb0b2a8e62 # Body text
            handle: bodyText2
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: abe1c852-ee4e-4f47-a333-5e3172692f2b
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 3373592e-35fe-4121-af0d-eaff0f329ea5
        userCondition: null
handle: media
hasTitleField: true
icon: ''
name: Media
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: ''
titleTranslationKeyFormat: null
titleTranslationMethod: site
