color: null
fieldLayouts:
  ee9ed938-ad65-46bd-b7c8-38d2d12afe61:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2024-10-29T22:46:51+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: c9d201ab-4c76-4b6b-99a3-312a916da6cd
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: a682608c-60ed-4883-b1a4-f19fc27e3f26
        userCondition: null
handle: newsPage
hasTitleField: true
icon: ''
name: 'News page'
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: ''
titleTranslationKeyFormat: null
titleTranslationMethod: site
