color: null
fieldLayouts:
  098f0f21-a5ec-48e4-b0f4-ae9cf6b4f4d9:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2024-10-15T02:39:26+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: d3d452b4-90b6-4afb-9bc6-d626d1f1a9d5
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-10-29T22:40:34+00:00'
            elementCondition: null
            fieldUid: e4bcf9a3-fd68-455d-aa8c-b60cc9a5d8da # Image
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 7b2e96c4-57b8-4d77-a956-1fd92d3bae4a
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-10-15T02:55:38+00:00'
            elementCondition: null
            fieldUid: c2f33fbf-f2dd-4e2c-a73d-8fdb0b2a8e62 # Body text
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 7859a30b-50de-4097-a1d4-0d7e4a2f6883
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: c6009cc1-3563-4b28-afef-150069919a32
        userCondition: null
handle: newsEntry
hasTitleField: true
icon: ''
name: 'News Entry'
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: ''
titleTranslationKeyFormat: null
titleTranslationMethod: site
