color: null
fieldLayouts:
  1ac7feaa-56a9-429e-8625-f24490143eaa:
    tabs:
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2024-11-12T10:49:57+13:00'
            elementCondition: null
            fieldUid: db31970c-ec27-4390-ab7d-245b1df9919d
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: db31970c-ec27-4390-ab7d-245b1df9919d
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-11-12T10:49:57+13:00'
            elementCondition: null
            fieldUid: 0d0bf617-bfdf-4fc7-9e76-2aa32bc75d7b
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 0d0bf617-bfdf-4fc7-9e76-2aa32bc75d7b
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-11-12T10:49:57+13:00'
            elementCondition: null
            fieldUid: d34816e0-8895-4436-8acd-67a67528cb58
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: d34816e0-8895-4436-8acd-67a67528cb58
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-11-12T10:49:57+13:00'
            elementCondition: null
            fieldUid: e151619f-aa93-4981-9b5b-bcdcf57d5cbf
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: e151619f-aa93-4981-9b5b-bcdcf57d5cbf
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-11-12T10:49:57+13:00'
            elementCondition: null
            fieldUid: 9972e84f-08e9-404e-9132-3e2e000741e3
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 9972e84f-08e9-404e-9132-3e2e000741e3
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 49d7e3b0-46ec-4970-a1e5-ae9d91461e21
        userCondition: null
handle: number
hasTitleField: false
icon: null
name: Number
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
