color: null
fieldLayouts:
  f3cde977-200d-4df0-8b47-a5f1a2b34751:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2024-10-14T20:50:51+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 417eaee2-0762-40f0-967c-c4cf247bba4b
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-10-14T20:54:16+00:00'
            elementCondition: null
            fieldUid: 046855ef-71bb-4c67-a58a-356e4bd73c27 # Heading
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: d9d8b7cb-72d3-4ce8-9e23-3468366b0215
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-10-14T21:05:42+00:00'
            elementCondition: null
            fieldUid: c2f33fbf-f2dd-4e2c-a73d-8fdb0b2a8e62 # Body text
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: a84b22a6-ddd9-4e4c-bda9-3274268b91ee
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-10-14T21:05:42+00:00'
            elementCondition: null
            fieldUid: e4bcf9a3-fd68-455d-aa8c-b60cc9a5d8da # Image
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: fbbd811e-ef7f-4eb9-a8b5-825f08cadc60
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-10-14T21:05:42+00:00'
            elementCondition: null
            fieldUid: c2f33fbf-f2dd-4e2c-a73d-8fdb0b2a8e62 # Body text
            handle: bodyText2
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 83b67a26-7a17-4778-b466-de905af144a7
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-10-14T21:05:42+00:00'
            elementCondition: null
            type: craft\fieldlayoutelements\HorizontalRule
            uid: 9c8a99fe-b6cb-4c90-bf5c-b2fb6d059ebb
            userCondition: null
          -
            dateAdded: '2024-10-14T21:05:42+00:00'
            elementCondition: null
            fieldUid: 046855ef-71bb-4c67-a58a-356e4bd73c27 # Heading
            handle: heading2
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: c4532133-9c7b-4706-8024-204cabf01422
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-10-14T21:05:42+00:00'
            elementCondition: null
            fieldUid: c2f33fbf-f2dd-4e2c-a73d-8fdb0b2a8e62 # Body text
            handle: bodyText3
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: d01eeeef-38e3-44a0-b551-92d52fab8d87
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-10-14T21:05:42+00:00'
            elementCondition: null
            type: craft\fieldlayoutelements\HorizontalRule
            uid: 182a31d5-0f67-4ce8-ba52-d894267c7294
            userCondition: null
          -
            dateAdded: '2024-10-14T21:05:42+00:00'
            elementCondition: null
            fieldUid: 046855ef-71bb-4c67-a58a-356e4bd73c27 # Heading
            handle: heading3
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: af70c7d3-53b9-4a53-8bc7-2bf19e97ffce
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-10-14T21:05:42+00:00'
            elementCondition: null
            fieldUid: c2f33fbf-f2dd-4e2c-a73d-8fdb0b2a8e62 # Body text
            handle: bodyText4
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 1710c5dc-42ad-4bbd-acd3-64c55cd4c6e1
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-10-14T21:05:42+00:00'
            elementCondition: null
            type: craft\fieldlayoutelements\HorizontalRule
            uid: 726e5c81-03b1-438c-98e3-afc655012791
            userCondition: null
          -
            dateAdded: '2024-10-14T21:05:42+00:00'
            elementCondition: null
            fieldUid: 046855ef-71bb-4c67-a58a-356e4bd73c27 # Heading
            handle: heading4
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 2338c1f3-5bd7-48aa-8dad-1c91cc1d5ae7
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-10-14T21:05:42+00:00'
            elementCondition: null
            fieldUid: c2f33fbf-f2dd-4e2c-a73d-8fdb0b2a8e62 # Body text
            handle: bodyText5
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 741e00ef-3001-43dc-a1c3-255e7f6e767b
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-10-14T21:05:42+00:00'
            elementCondition: null
            type: craft\fieldlayoutelements\HorizontalRule
            uid: b608faa4-da9b-4c5a-ae34-e9a893d8bf66
            userCondition: null
          -
            dateAdded: '2024-10-14T21:05:42+00:00'
            elementCondition: null
            fieldUid: 046855ef-71bb-4c67-a58a-356e4bd73c27 # Heading
            handle: heading5
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 85437a82-7a60-4e8e-afcd-8c5aab1b217c
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-10-14T21:05:42+00:00'
            elementCondition: null
            fieldUid: c2f33fbf-f2dd-4e2c-a73d-8fdb0b2a8e62 # Body text
            handle: bodyText6
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: a2ea18c7-02af-49d7-ab73-cb52a7529a66
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-10-14T21:05:42+00:00'
            elementCondition: null
            type: craft\fieldlayoutelements\HorizontalRule
            uid: 439800a4-86b6-48cf-bc6e-3ab48721d064
            userCondition: null
          -
            dateAdded: '2024-10-14T21:05:42+00:00'
            elementCondition: null
            fieldUid: 046855ef-71bb-4c67-a58a-356e4bd73c27 # Heading
            handle: heading6
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 4eeab1bb-89bd-4800-b01f-820a5f52de9b
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-10-14T21:05:42+00:00'
            elementCondition: null
            fieldUid: c2f33fbf-f2dd-4e2c-a73d-8fdb0b2a8e62 # Body text
            handle: bodyText7
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: e7c021dc-690c-4bf7-945e-67d4f5c4b7be
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: d82ce14f-3a93-4463-8e59-d16e5a4e8ae9
        userCondition: null
handle: ourPrinciples
hasTitleField: false
icon: ''
name: 'Our Principles'
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: 'Our Principles'
titleTranslationKeyFormat: null
titleTranslationMethod: site
