color: null
fieldLayouts:
  49bdab08-b4bc-4c46-81bd-8961dc6cf3fa:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2024-09-30T20:58:21+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: bfd1fd6e-a31e-4ebf-8dfc-152856c50f63
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: ca980d1e-b425-4979-b517-b70704a8a5d4
        userCondition: null
handle: products
hasTitleField: true
icon: ''
name: Products
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: ''
titleTranslationKeyFormat: null
titleTranslationMethod: site
