color: null
fieldLayouts:
  f63d0f5e-acc0-4c92-8d7d-20c4149fa361:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2024-11-03T22:27:26+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 8385eb1f-bc40-40ef-a916-c7a38d5ad543
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-11-03T22:46:06+00:00'
            elementCondition: null
            fieldUid: f90b17ae-f61f-4247-a70e-729542fe2fb4 # Shop Category
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: d8662954-cf16-45f9-85fd-5c646441cf7a
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 9bfc053b-62bf-4963-9638-5ff0972db577
        userCondition: null
handle: product
hasTitleField: true
icon: ''
name: Product
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: ''
titleTranslationKeyFormat: null
titleTranslationMethod: site
