color: null
fieldLayouts:
  f46f26fe-0cb5-4d95-a623-1007fb9410b3:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2024-10-14T22:50:25+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 05dd7d20-f3bf-4f24-9460-4d1c99f3f4ed
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-10-14T22:53:05+00:00'
            elementCondition: null
            fieldUid: 046855ef-71bb-4c67-a58a-356e4bd73c27 # Heading
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 3a22931d-5449-4d47-9ece-084e232d240f
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-10-14T22:53:05+00:00'
            elementCondition: null
            fieldUid: c2f33fbf-f2dd-4e2c-a73d-8fdb0b2a8e62 # Body text
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: e9e09dcd-80f0-4534-8968-467e01d3beee
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-10-14T22:53:05+00:00'
            elementCondition: null
            fieldUid: 046855ef-71bb-4c67-a58a-356e4bd73c27 # Heading
            handle: heading2
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 4aba1f5a-7048-4e39-bedf-07c69fcf4b28
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-10-14T22:53:05+00:00'
            elementCondition: null
            fieldUid: c2f33fbf-f2dd-4e2c-a73d-8fdb0b2a8e62 # Body text
            handle: bodyText2
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: c00b6e4b-ffd2-4074-abc7-db97143c943c
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-10-14T22:53:05+00:00'
            elementCondition: null
            fieldUid: 046855ef-71bb-4c67-a58a-356e4bd73c27 # Heading
            handle: heading3
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: a72320fb-2a8b-464e-8b96-7085d47f1493
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-10-14T22:53:05+00:00'
            elementCondition: null
            fieldUid: c2f33fbf-f2dd-4e2c-a73d-8fdb0b2a8e62 # Body text
            handle: bodyText3
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 2ee4c8cd-7912-4a33-8257-1d9af0484052
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-10-14T22:57:56+00:00'
            elementCondition: null
            fieldUid: 9642a918-c523-42c5-b282-682e9739bfc3 # Button Link
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: c9858e60-0054-4c45-8f06-62dd7cdf06e8
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-10-14T22:57:56+00:00'
            elementCondition: null
            fieldUid: e4bcf9a3-fd68-455d-aa8c-b60cc9a5d8da # Image
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 6a8535c7-53f2-474c-aab6-a341eab904ea
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-10-14T22:57:56+00:00'
            elementCondition: null
            fieldUid: 9642a918-c523-42c5-b282-682e9739bfc3 # Button Link
            handle: buttonLink2
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: a3715cec-aa92-40b2-808e-80d8b015bdc3
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-10-14T22:57:56+00:00'
            elementCondition: null
            fieldUid: e4bcf9a3-fd68-455d-aa8c-b60cc9a5d8da # Image
            handle: image2
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: f4d18d5a-1dee-42b8-96a1-66e7ed126b5c
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: a32f9909-df40-4921-bb19-a25245c34de0
        userCondition: null
handle: shippingInformation
hasTitleField: false
icon: ''
name: 'Shipping Information'
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: 'Shipping Information'
titleTranslationKeyFormat: null
titleTranslationMethod: site
