color: null
fieldLayouts:
  3a56d986-7e12-4d4c-8c19-0c7e256bfde0:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2024-09-30T21:54:31+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 8e59e94c-8f15-4507-bd3b-cf41a66c2f35
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-09-30T22:28:14+00:00'
            elementCondition: null
            fieldUid: c2f33fbf-f2dd-4e2c-a73d-8fdb0b2a8e62 # Body text
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 22ec6636-0a82-4a60-97f8-479e33f3b862
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-09-30T22:34:42+00:00'
            elementCondition: null
            fieldUid: 9c5edb31-d275-4b0d-88b7-a8f1395e194c # Button Text
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: c0355381-60c6-46db-a1de-b7eedac8c243
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-09-30T22:28:14+00:00'
            elementCondition: null
            fieldUid: 9642a918-c523-42c5-b282-682e9739bfc3 # Button Link
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 87d02280-1745-47b3-88ce-37a4e084441a
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-09-30T22:28:14+00:00'
            elementCondition: null
            fieldUid: e4bcf9a3-fd68-455d-aa8c-b60cc9a5d8da # Image
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 0db2bbb8-db87-439c-ae3f-6241803ca027
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 0683102c-9a39-4244-b842-0c9966a7b619
        userCondition: null
handle: ventilation
hasTitleField: true
icon: ''
name: Ventilation
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: ''
titleTranslationKeyFormat: null
titleTranslationMethod: site
