color: null
fieldLayouts:
  73543f4e-d254-4cb5-9a08-351f4ccc476f:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2024-09-30T21:55:14+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: bc3fef12-26c1-45d8-a7ae-592f7f687983
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-10-14T22:14:44+00:00'
            elementCondition: null
            fieldUid: 046855ef-71bb-4c67-a58a-356e4bd73c27 # Heading
            handle: heading4
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 00d36a2a-3e81-4370-81cf-5da2b246fa37
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-09-30T22:28:34+00:00'
            elementCondition: null
            fieldUid: c2f33fbf-f2dd-4e2c-a73d-8fdb0b2a8e62 # Body text
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 619f08b7-1b2e-44de-ab0b-faf342c0acbe
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-09-30T22:28:34+00:00'
            elementCondition: null
            fieldUid: 9c5edb31-d275-4b0d-88b7-a8f1395e194c # Button Text
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: f1042f23-75ca-4ccf-bf57-8455e22b457e
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-10-10T00:07:19+00:00'
            elementCondition: null
            fieldUid: e4bcf9a3-fd68-455d-aa8c-b60cc9a5d8da # Image
            handle: image5
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 1cd09352-3264-4fa9-a751-a0838ed76329
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-10-10T00:07:19+00:00'
            elementCondition: null
            heading: ''
            type: craft\fieldlayoutelements\Heading
            uid: 89481cfb-e8a5-48e6-a61d-9119e48274f4
            userCondition: null
          -
            dateAdded: '2024-10-09T22:27:56+00:00'
            elementCondition: null
            fieldUid: c2f33fbf-f2dd-4e2c-a73d-8fdb0b2a8e62 # Body text
            handle: bodyText2
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 52443497-a9f9-48b2-a00c-48a2504f787c
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-09-30T22:28:34+00:00'
            elementCondition: null
            fieldUid: e4bcf9a3-fd68-455d-aa8c-b60cc9a5d8da # Image
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 6450d6ee-fec5-4af5-9e00-a4299b51cf60
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-10-10T01:47:14+00:00'
            elementCondition: null
            heading: ''
            type: craft\fieldlayoutelements\Heading
            uid: 083a994e-d86b-4a3f-b176-a24043b22335
            userCondition: null
          -
            dateAdded: '2024-10-10T01:47:14+00:00'
            elementCondition: null
            fieldUid: 046855ef-71bb-4c67-a58a-356e4bd73c27 # Heading
            handle: heading3
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: d4e67310-0662-4adf-9a0b-cc3c3c74f9bf
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-10-10T01:47:14+00:00'
            elementCondition: null
            fieldUid: 17fb6c25-a3f3-4550-8b67-398469d79e9a # Product Matrix
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: c4e8fd83-1cf3-49fc-895c-1b7ec22d210c
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-10-09T23:24:28+00:00'
            elementCondition: null
            heading: 'Icon section'
            type: craft\fieldlayoutelements\Heading
            uid: 1075f921-099d-4cdc-b4f5-1e73f605f7d7
            userCondition: null
          -
            dateAdded: '2024-10-09T23:24:28+00:00'
            elementCondition: null
            fieldUid: 046855ef-71bb-4c67-a58a-356e4bd73c27 # Heading
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 026ab657-c44f-47fc-8c36-a333068e30c2
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-10-09T23:24:28+00:00'
            elementCondition: null
            fieldUid: e4bcf9a3-fd68-455d-aa8c-b60cc9a5d8da # Image
            handle: image2
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 6e5122a3-a17a-405d-8098-92ed935a76f0
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-10-09T23:24:28+00:00'
            elementCondition: null
            fieldUid: c2f33fbf-f2dd-4e2c-a73d-8fdb0b2a8e62 # Body text
            handle: bodyText3
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: d9804b1d-579b-4fcb-ac33-6eb22f9191e1
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-10-09T23:24:28+00:00'
            elementCondition: null
            fieldUid: e4bcf9a3-fd68-455d-aa8c-b60cc9a5d8da # Image
            handle: image3
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: f50bead8-f05f-4d7f-a771-148a08ccca02
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-10-09T23:24:28+00:00'
            elementCondition: null
            fieldUid: c2f33fbf-f2dd-4e2c-a73d-8fdb0b2a8e62 # Body text
            handle: bodyText4
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 7c1d5fc8-3dce-4ec5-a0f8-4191269e07c2
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-10-09T23:24:28+00:00'
            elementCondition: null
            fieldUid: e4bcf9a3-fd68-455d-aa8c-b60cc9a5d8da # Image
            handle: image4
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: c9d0a772-b123-41fe-97bb-8c42f73a50c4
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-10-09T23:24:28+00:00'
            elementCondition: null
            fieldUid: c2f33fbf-f2dd-4e2c-a73d-8fdb0b2a8e62 # Body text
            handle: bodyText5
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 5f393944-d598-4b83-95aa-5694c6fe66c3
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-10-10T00:48:05+00:00'
            elementCondition: null
            heading: 'Logo section'
            type: craft\fieldlayoutelements\Heading
            uid: a008a2f4-6d8b-4799-a5fd-27e98ee13563
            userCondition: null
          -
            dateAdded: '2024-10-10T00:48:05+00:00'
            elementCondition: null
            fieldUid: e4bcf9a3-fd68-455d-aa8c-b60cc9a5d8da # Image
            handle: image6
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: fc05acdd-587c-49e9-9891-df0f4e8adae7
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-10-10T02:54:18+00:00'
            elementCondition: null
            fieldUid: e4bcf9a3-fd68-455d-aa8c-b60cc9a5d8da # Image
            handle: image7
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: d926ef99-1bdb-4d18-a6f0-bcc7c4a7ea5a
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-10-10T02:54:18+00:00'
            elementCondition: null
            fieldUid: e4bcf9a3-fd68-455d-aa8c-b60cc9a5d8da # Image
            handle: image8
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: e9034cea-af20-4f0c-9e07-6dcfaf1d8f0c
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-10-10T00:48:05+00:00'
            elementCondition: null
            fieldUid: c2f33fbf-f2dd-4e2c-a73d-8fdb0b2a8e62 # Body text
            handle: bodyText6
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 878e97c9-2d7a-427a-adf9-f6698db1c09b
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-10-10T01:02:07+00:00'
            elementCondition: null
            heading: 'Form section'
            type: craft\fieldlayoutelements\Heading
            uid: 83ddb283-004d-428d-ad76-2c84cf3be26a
            userCondition: null
          -
            dateAdded: '2024-10-10T01:02:07+00:00'
            elementCondition: null
            fieldUid: 046855ef-71bb-4c67-a58a-356e4bd73c27 # Heading
            handle: heading2
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 88fd25a2-4c89-4155-9ec8-8f0a4cb9f96b
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-10-10T01:02:07+00:00'
            elementCondition: null
            fieldUid: c2f33fbf-f2dd-4e2c-a73d-8fdb0b2a8e62 # Body text
            handle: bodyText7
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 614fbbc9-cc73-4fee-b88a-819154ae5f42
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 4096d7cc-4e8f-458e-b247-c28a1bc4d9c1
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2024-10-29T22:13:49+00:00'
            elementCondition: null
            fieldUid: e4bcf9a3-fd68-455d-aa8c-b60cc9a5d8da # Image
            handle: image9
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: d0264768-88ff-495c-9e2c-764b524a482e
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-10-29T22:17:45+00:00'
            elementCondition: null
            fieldUid: 046855ef-71bb-4c67-a58a-356e4bd73c27 # Heading
            handle: heading5
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: d7874621-958b-45c7-a212-25bf7d4a1d1b
            userCondition: null
            warning: null
            width: 100
        name: 'Homepage - Explore Our Services Section'
        uid: 9aae3b9b-ccc3-410b-b08f-66e87aa7814e
        userCondition: null
handle: windows
hasTitleField: false
icon: ''
name: Windows
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: Windows
titleTranslationKeyFormat: null
titleTranslationMethod: site
