headingLevels:
  - 2
  - 3
  - 4
  - 5
  - 6
name: Simple
options:
  alignment:
    options:
      - left
      - right
toolbar:
  - heading
  - '|'
  - bold
  - italic
  - link
  - bulletedList
  - numberedList
  - sourceEditing
  - alignment
  - insertTable
  - insertImage
