defaultPlacement: end
fieldLayouts:
  f30306ba-c4bb-4eb0-894f-e6e9f71e9dd5:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2024-11-03T20:01:27+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\TitleField
            uid: 80da12b9-618b-4965-96c6-566a8d26e77f
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-11-03T22:45:46+00:00'
            elementCondition: null
            fieldUid: c2f33fbf-f2dd-4e2c-a73d-8fdb0b2a8e62 # Body text
            handle: null
            includeInCards: false
            instructions: null
            label: Description
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 83295026-b482-4da0-86e9-c558967fdb69
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: b019a4d9-fd6d-45c7-aed2-ca5e2b9c8571
        userCondition: null
handle: shopCategories
name: 'Shop Categories'
siteSettings:
  24b1554e-bb4c-4639-aaa1-13d20c08f54c: # Five Merchants
    hasUrls: true
    template: _singles/category.twig
    uriFormat: 'shop/{slug}'
structure:
  maxLevels: 3
  uid: 8703e6a2-daa5-4d88-b43f-853c49e22b05
