baseUrl: $PRIMARY_SITE_URL
enabled: true
handle: default
hasUrls: true
language: en-GB
name: 'Five Merchants'
primary: true
siteGroup: ac579ea2-87ac-4736-92ca-cdd00be1027e # Five Merchants
sortOrder: 1
