columnSuffix: null
handle: bodyText
instructions: null
name: 'Body text'
searchable: false
settings:
  availableTransforms: ''
  availableVolumes: '*'
  ckeConfig: fd350744-0e46-410e-afa7-0477fa19889c # Simple
  createButtonLabel: null
  defaultTransform: null
  enableSourceEditingForNonAdmins: false
  purifierConfig: null
  purifyHtml: true
  showUnpermittedFiles: false
  showUnpermittedVolumes: false
  showWordCount: false
  wordLimit: null
translationKeyFormat: null
translationMethod: none
type: craft\ckeditor\Field
