columnSuffix: null
handle: shopCategory
instructions: null
name: 'Shop Category'
searchable: false
settings:
  allowSelfRelations: false
  branchLimit: null
  maintainHierarchy: false
  maxRelations: null
  minRelations: 1
  selectionLabel: null
  showCardsInGrid: false
  showSiteMenu: false
  source: 'group:eecc1b1e-edb1-4b07-980c-b50aa133be51' # Shop Categories
  targetSiteId: null
  validateRelatedElements: false
  viewMode: list
translationKeyFormat: null
translationMethod: none
type: craft\fields\Categories
