fieldLayouts:
  465f4f92-2ac5-4bdd-9b5c-c926f298d3a2:
    tabs:
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2024-10-14T02:51:51+00:00'
            elementCondition: null
            fieldUid: c2f33fbf-f2dd-4e2c-a73d-8fdb0b2a8e62 # Body text
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 1bea2d38-6e4e-4928-8240-cb18e40f05fb
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-10-14T02:51:51+00:00'
            elementCondition: null
            fieldUid: 9c5edb31-d275-4b0d-88b7-a8f1395e194c # Button Text
            handle: null
            includeInCards: false
            instructions: null
            label: 'Login Text'
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: c6faa4bc-6d0b-4e3a-9b4e-400324739896
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-10-14T02:51:51+00:00'
            elementCondition: null
            fieldUid: 9642a918-c523-42c5-b282-682e9739bfc3 # Button Link
            handle: null
            includeInCards: false
            instructions: null
            label: 'Login Link'
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 9bccac6a-3796-4d30-8aa2-70717a9a36e5
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-10-14T02:51:51+00:00'
            elementCondition: null
            fieldUid: 9642a918-c523-42c5-b282-682e9739bfc3 # Button Link
            handle: buttonLink2
            includeInCards: false
            instructions: null
            label: 'Facebook Url'
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: b8cfd581-b545-4026-a384-808c92a4ab20
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-10-14T02:51:51+00:00'
            elementCondition: null
            fieldUid: 9642a918-c523-42c5-b282-682e9739bfc3 # Button Link
            handle: buttonLink3
            includeInCards: false
            instructions: null
            label: 'Instagram Url'
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 693532ed-35f5-4560-affe-ce5b1ed0f50c
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-10-14T02:52:36+00:00'
            elementCondition: null
            fieldUid: 551c2e50-7554-49f0-a36d-28193755ebb3 # Page List
            handle: null
            includeInCards: false
            instructions: null
            label: 'Footer Navigation'
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: ca6d24c5-0a78-4531-84db-db869743ef20
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 84ff9af1-0739-4e70-a0f4-264ea1dd58ff
        userCondition: null
handle: footer
name: Footer
sortOrder: 1
