defaultPlacement: end
enableVersioning: true
entryTypes:
  - 8621b75a-0db6-47a4-bdaf-f4527740bc6f # Blower door testing
handle: blowerDoorTesting
maxAuthors: 1
name: 'Blower Door Testing'
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - urlFormat
        - '{url}'
      -
        - refresh
        - '1'
propagationMethod: all
siteSettings:
  24b1554e-bb4c-4639-aaa1-13d20c08f54c: # Five Merchants
    enabledByDefault: true
    hasUrls: true
    template: _singles/blower-door-testing.twig
    uriFormat: services/blower-door-testing
type: single
