defaultPlacement: end
enableVersioning: true
entryTypes:
  - aad57e69-bf90-44e2-8b57-e467ecbe68b6 # Home performance audits
handle: homePerformanceAudits
maxAuthors: 1
name: 'Home Performance Audits'
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - urlFormat
        - '{url}'
      -
        - refresh
        - '1'
propagationMethod: all
siteSettings:
  24b1554e-bb4c-4639-aaa1-13d20c08f54c: # Five Merchants
    enabledByDefault: true
    hasUrls: true
    template: _singles/home-performance-audits.twig
    uriFormat: services/home-performance-audits
type: single
