defaultPlacement: end
enableVersioning: true
entryTypes:
  - 495d481a-b157-408f-8f5a-18a8150e3b96 # News Entry
handle: newsEntry
maxAuthors: 1
name: 'News Entry'
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - urlFormat
        - '{url}'
      -
        - refresh
        - '1'
propagationMethod: all
siteSettings:
  24b1554e-bb4c-4639-aaa1-13d20c08f54c: # Five Merchants
    enabledByDefault: true
    hasUrls: true
    template: news/_entry.twig
    uriFormat: 'news/{slug}'
type: channel
