defaultPlacement: end
enableVersioning: true
entryTypes:
  - 6931674c-a2a8-4db1-8762-2c5d2d78aad3 # News page
handle: news
maxAuthors: 1
name: News
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - urlFormat
        - '{url}'
      -
        - refresh
        - '1'
propagationMethod: all
siteSettings:
  24b1554e-bb4c-4639-aaa1-13d20c08f54c: # Five Merchants
    enabledByDefault: true
    hasUrls: true
    template: news/index.twig
    uriFormat: news
type: single
