defaultPlacement: end
enableVersioning: true
entryTypes:
  - 4d60f25b-0a29-413f-99b1-0354ac86a120 # Products
handle: products
maxAuthors: 1
name: Products
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - urlFormat
        - '{url}'
      -
        - refresh
        - '1'
propagationMethod: all
siteSettings:
  24b1554e-bb4c-4639-aaa1-13d20c08f54c: # Five Merchants
    enabledByDefault: true
    hasUrls: true
    template: _singles/products.twig
    uriFormat: products
type: single
