defaultPlacement: end
enableVersioning: true
entryTypes:
  - d91c5e6a-22b4-4624-9042-0dd7947b6434 # Conditions Template
handle: returnsPolicy
maxAuthors: 1
name: 'Returns Policy'
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - urlFormat
        - '{url}'
      -
        - refresh
        - '1'
propagationMethod: all
siteSettings:
  24b1554e-bb4c-4639-aaa1-13d20c08f54c: # Five Merchants
    enabledByDefault: true
    hasUrls: true
    template: _singles/returns-policy.twig
    uriFormat: returns-policy
type: single
