defaultPlacement: end
enableVersioning: true
entryTypes:
  - c128454f-a52d-4dc8-aa3e-e134fcd2c530 # Ventilation
handle: ventilation
maxAuthors: 1
name: Ventilation
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - urlFormat
        - '{url}'
      -
        - refresh
        - '1'
propagationMethod: all
siteSettings:
  24b1554e-bb4c-4639-aaa1-13d20c08f54c: # Five Merchants
    enabledByDefault: true
    hasUrls: true
    template: _singles/ventilation.twig
    uriFormat: about/ventilation
type: single
