defaultPlacement: end
enableVersioning: true
entryTypes:
  - 2284ed3a-e66c-4af9-9f3c-4be5caaa4b7c # Windows
handle: windows
maxAuthors: 1
name: Windows
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - urlFormat
        - '{url}'
      -
        - refresh
        - '1'
propagationMethod: all
siteSettings:
  24b1554e-bb4c-4639-aaa1-13d20c08f54c: # Five Merchants
    enabledByDefault: true
    hasUrls: true
    template: _singles/windows.twig
    uriFormat: about/windows
type: single
